---

- import_tasks: configure-kafka3-datasource.yml
  tags:
    - configure-kafka3-datasource

- import_tasks: configure-slack.yml
  tags:
    - configure-slack

- import_tasks: provision-monitoring-dashboard.yml
  tags:
    - provision-monitoring-dashboard

- import_tasks: provision-topic-overview-dashboard.yml
  tags:
    - provision-topic-overview-dashboard

- import_tasks: provision-insolvency-dashboard.yml
  tags:
    - provision-insolvency-dashboard
